Bookstore/Components/CartSummaryViewComponent.cs
using System;
using System.Linq;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket { get; }

        public CartSummaryViewComponent (Basket b)
        {
            basket = b;
        }

        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Bookstore/Components/CategoryViewComponent.cs
using System;
using System.Linq;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public CategoryViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["Category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Bookstore/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>@Model.Title</h4>

        <h5><span class="badge badge-secondary" style="float:right">Author: @Model.Author</span></h5>
        
    </div>

    <ul>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn </li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Pages: @Model.PageCount</li>
        <li>Price: $@Model.Price</li>
    </ul>

    <form method="post" asp-page="/Buy">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-info btn-sm float-end" style="float:right">Add To Cart</button>
        </span>
    </form>

</div>

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Gloock" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignIn">SignIn</a>
                        </li>
                       
                    </ul>
                </div>
                <div class="ml-auto">
                    <vc:cart-summary />
                </div>

            </div>
        </nav>
    </header>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:category></vc:category>
        </div>


        <div class="col-9">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>




    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Bookstore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>